---
- name: "Fortigate"
  hosts: FW-1
  tasks:
    - include_role:
        name: fortios_enable_lldp

    - name: "Add vlan HERP"
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          allowaccess:
            - "ping"
          interface: "port2"
          ip: "10.1.2.1/24"
          name: "HERP"
          type: "vlan"
          vlanid: 2
          vdom: "root"

    - name: "Add vlan DERP"
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          allowaccess:
            - "ping"
          interface: "port2"
          ip: "10.1.3.1/24"
          name: "DERP"
          type: "vlan"
          vlanid: 3
          vdom: "root"

- name: "Arista"
  hosts: "EOS"
  tasks:
    - name: "Add vlans"
      arista.eos.eos_vlans:
        state: merged
        config:
          - name: HERP
            vlan_id: 2
          - name: DERP
            vlan_id: 3

    - include_role:
        name: arista_trunk

    - include_role:
        name: arista_stp_root

