---
- name: "Arista"
  hosts: "EOS"
  tasks:
    - name: "Add vlans"
      arista.eos.eos_vlans:
        state: merged
        config:
          - name: HERP
            vlan_id: 2
          - name: DERP
            vlan_id: 3

    - name: "Gather lldp interfaces facts from the device"
      arista.eos.eos_command:
        commands:
          - command: show lldp neighbors
            output: json
      register: lldp_neighbors

    - debug:
        var: lldp_neighbors.stdout.0.lldpNeighbors

    - name: "Enable VLANs on trunk ports"
      arista.eos.eos_config:
        parents: interface {{ nbr.port }}
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan add 2
          - switchport trunk allowed vlan add 3
      loop: "{{ lldp_neighbors.stdout.0.lldpNeighbors }}"
      loop_control:
        loop_var: nbr
      when: 
        - '"Ethernet" in nbr.port'
        - '"fw-" in nbr.neighborDevice or "sw-" in nbr.neighborDevice'


- name: "Fortigate"
  hosts: FORTIOS
  tasks:
    - name: "Add vlan HERP"
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          allowaccess:
            - "ping"
          interface: "port2"
          ip: "10.1.2.1/24"
          name: "HERP"
          type: "vlan"
          vlanid: 2
          vdom: "root"

    - name: "Add vlan DERP"
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          allowaccess:
            - "ping"
          interface: "port2"
          ip: "10.1.3.1/24"
          name: "DERP"
          type: "vlan"
          vlanid: 3
          vdom: "root"
