---

- name: "Create {{ fgt }} API user and generate access-token"
  ansible.builtin.shell: |
    set timeout 30
    spawn ssh admin@{{ hostvars[fgt]['ansible_host'] }}
    expect {
      "This key is not known by any other names" {
        send "yes\n"
        exp_continue
      }
      "password: " {
        send "admin\n"
      }
    }
    expect "fw-1 "
    send "config system api-user\n"
    expect "fw-1 "
    send "edit ansible\n"
    expect "fw-1 "
    send "set accprofile prof_admin\n"
    expect "fw-1 "
     send "end\n"
    expect "fw-1 "
    send "execute api-user generate-key ansible\n"
    expect "fw-1 "
    send "exit\n"
  args:
    executable: /usr/bin/expect
  register: output

- name: "Create access_token variable from 'NEW API key' line output"
  set_fact:
    access_token:  "{{ item.split()[-1] }}"
  when: '"New API key" in item'
  loop: "{{ output.stdout_lines }}"

- name: "Print {{ fgt }} access token"
  debug:
    var: access_token

- name: "Create host_vars/ folder"
  ansible.builtin.file:
    path: "host_vars"
    state: directory

- name: "Generate host_vars/{{ fgt }}.yml"
  ansible.builtin.blockinfile:
    create: true
    path: host_vars/{{ fgt }}.yml
    block: |
      ansible_user: ansible
      ansible_httpapi_session_key:
        access_token: {{ access_token }}

