---

- name: "Get LLDP neighbors"
  arista.eos.eos_command:
    commands: 
      - command: show lldp neighbors
        output: json
  register: lldp_neighbors

### OUTPUT ###
# ok: [SW-1] =>
#   lldp_neighbors:
#     changed: false
#     failed: false
#     stdout:
#     - lldpNeighbors:
#       - neighborDevice: fw-1
#         neighborPort: port2
#         port: Ethernet1
#         ttl: 120
#       - neighborDevice: sw-2
#         neighborPort: Ethernet1
#         port: Ethernet2
#         ttl: 120
#       - neighborDevice: sw-2
#         neighborPort: Management0
#         port: Management0
#         ttl: 120

- name: "Set STP root"
  arista.eos.eos_config:
    lines: spanning-tree mst 0 priority 8192
  loop: "{{ lldp_neighbors.stdout.0.lldpNeighbors }}"
  loop_control:
    loop_var: nbr
  when: '"fw-" in nbr.neighborDevice'
 
